# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/

obj-$(CONFIG_PM_SLEEP)		+= pm.o sleep.o
obj-$(CONFIG_CPU_S5PV210)	+= s5pv210.o
obj-$(CONFIG_CPU_S5P6442)	+= s5p6442.o
